### ISSUE TITLE
Cuda Error in Cuda 11.7  Ubuntu20.04

### ISSUE THREAD

**Issue by Causality-C** [DavidXu-JJ/PoissonRecon_GPU#4]
Hello, thank you for your hard work putting this repo together. I am trying to run the code in a docker container and have been getting a weird error, details below

DockerFile

```docker
FROM nvidia/cuda:11.7.1-cudnn8-devel-ubuntu20.04

LABEL name="PoissonRecon_GPU"

ENV DEBIAN_FRONTEND=noninteractive

# update package lists and install git, wget, vim, libegl1-mesa-dev, and libglib2.0-0
RUN apt-get update && apt-get install -y build-essential git wget vim libegl1-mesa-dev libglib2.0-0 unzip git tree cmake>=

WORKDIR /workspace
RUN wget https://www.cs.jhu.edu/~misha/Code/PoissonRecon/bunny.points.ply
COPY  . .
```

I got `bunny.points.ply` from https://www.cs.jhu.edu/~misha/Code/PoissonRecon/bunny.points.ply

**Error**
```
root@61d911b84d5d:/workspace/build# ./GPU_PoissonRecon
Total points number:362271 ,Read takes:0.169649s
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  radix_sort: failed on 2nd step: cudaErrorInvalidValue: invalid argument
Aborted
```

which seems to be pointing at this code

```
    /**     Step 3: sort all sample points      */
    thrust::device_ptr<long long> key_ptr=thrust::device_pointer_cast<long long>(key);
    thrust::sort_by_key(key_ptr,key_ptr+count,samplePoints_d);
    cudaDeviceSynchronize();

    key_ptr=thrust::device_pointer_cast<long long>(key_backup);
    thrust::sort_by_key(key_ptr,key_ptr+count,sampleNormals_d);
    cudaDeviceSynchronize();
```

**Comment by DavidXu-JJ** [comment]
Hi, it seems that you open a pull request. Have you solve your problem?

**Comment by DavidXu-JJ** [comment]
It seems that the current newest thrust api has some changes about the arguments number.

```
https://nvidia.github.io/cccl/thrust/api/function_group__sorting_1ga667333ee2e067bb7da3fb1b8ab6d348c.html
```

Unfortunately, I recently have reinstalled my nvidia driver and cuda environment on my laptop. So I'm unable to track the old thrust version used here when I was actively developing it.

**Comment by DavidXu-JJ** [comment]
It still remains some logs of this program on my laptop running in debug mode. Hope it helps for the debugging.
```
Total points number:362271 ,Read takes:0.099791s
GPU NodeArray build takes:0.187948s
NodeArray_sz:1393505
CPU generate precomputed inner product table takes:0.131012s
Compute Vector Field takes:0.024192s
Precompute Function index of node takes:0.005923s
left:1513,right:1393505
Compute finer depth nodes' divergence takes:0.095290s
Compute coarser depth nodes' divergence takes:0.128186s
Depth 0 Itetation...
valNums:1
Starting [conjugateGradientMultiBlockCG]...
> GPU device has 16 Multi-Processors, SM 8.6 compute capabilities

GPU Final, residual = 3.517670e-09, kernel execution time = 0.228064 ms
Test Summary:  Error amount = 0.125000 
Depth 1 Itetation...
valNums:32
Starting [conjugateGradientMultiBlockCG]...
> GPU device has 16 Multi-Processors, SM 8.6 compute capabilities

GPU Final, residual = 2.080984e-10, kernel execution time = 0.223328 ms
Test Summary:  Error amount = 0.250000 
Depth 2 Itetation...
valNums:352
Starting [conjugateGradientMultiBlockCG]...
> GPU device has 16 Multi-Processors, SM 8.6 compute capabilities

GPU Final, residual = 5.330017e-06, kernel execution time = 0.386624 ms
Test Summary:  Error amount = 0.500000 
Depth 3 Itetation...
valNums:1800
Starting [conjugateGradientMultiBlockCG]...
> GPU device has 16 Multi-Processors, SM 8.6 compute capabilities

GPU Final, residual = 7.274163e-06, kernel execution time = 0.639616 ms
Test Summary:  Error amount = 0.500000 
Depth 4 Itetation...
valNums:6872
Starting [conjugateGradientMultiBlockCG]...
> GPU device has 16 Multi-Processors, SM 8.6 compute capabilities

GPU Final, residual = 6.377280e-06, kernel execution time = 0.765056 ms
Test Summary:  Error amount = 0.250000 
Depth 5 Itetation...
valNums:26680
Starting [conjugateGradientMultiBlockCG]...
> GPU device has 16 Multi-Processors, SM 8.6 compute capabilities

GPU Final, residual = 5.446308e-06, kernel execution time = 0.784288 ms
Test Summary:  Error amount = 0.187500 
Depth 6 Itetation...
valNums:106312
Starting [conjugateGradientMultiBlockCG]...
> GPU device has 16 Multi-Processors, SM 8.6 compute capabilities

GPU Final, residual = 9.066063e-06, kernel execution time = 1.265984 ms
Test Summary:  Error amount = 0.093750 
Depth 7 Itetation...
valNums:429344
Starting [conjugateGradientMultiBlockCG]...
> GPU device has 16 Multi-Processors, SM 8.6 compute capabilities

GPU Final, residual = 8.257334e-06, kernel execution time = 3.578496 ms
Test Summary:  Error amount = 0.046875 
Depth 8 Itetation...
valNums:1662992
Starting [conjugateGradientMultiBlockCG]...
> GPU device has 16 Multi-Processors, SM 8.6 compute capabilities

GPU Final, residual = 6.590612e-06, kernel execution time = 13.542080 ms
Test Summary:  Error amount = 0.019531 
Depth 9 Itetation...
valNums:5930096
Starting [conjugateGradientMultiBlockCG]...
> GPU device has 16 Multi-Processors, SM 8.6 compute capabilities

GPU Final, residual = 7.717600e-06, kernel execution time = 43.722206 ms
Test Summary:  Error amount = 0.006836 
Pure CG solving process takes:65.135742ms
GPU Laplacian Iteration takes:0.181181s
isoValue:-4560000.500000
GPU calculate isoValue takes:0.042142s
VertexArray_sz:2190708
GPU build VertexArray takes:0.066689s
EdgeArray_sz:4266544
GPU build EdgeArray takes:0.057794s
FaceArray_sz:4975542
GPU build FaceArray takes:0.049299s
Compute vertex implicit function value takes:0.227161s
Compute vexAddress takes:0.005231s
Compute triAddress takes:0.001293s
Generate interpolate vertices takes:0.489491s
Process Triangle indices takes:0.015676s
Starting processing the subdivide node
SubdivideNum:73074
GPU processing coarse subdivide nodes takes 6.483456s
Start the 6 depth finer subdivide nodes processing
Start the 7 depth finer subdivide nodes processing
Start the 8 depth finer subdivide nodes processing
GPU processing finer subdivide nodes takes 1.218858s
Output ply files takes 0.511188s
The whole project takes 10.021961s (including I/O)
```

**Comment by GateraGael** [comment]
Hello, I had the same exact issue as @Causality-C and I got it fixed by upgrading the base image in the dockerfile to the following :
```
nvcr.io/nvidia/cuda:12.2.2-cudnn8-devel-ubuntu22.04
```
However, where do we change octree depth in main.cu ?

**Comment by DavidXu-JJ** [comment]
Hi Gatera,
Thank you for your contribution. I will check if your solution works when it's convenient for me. (I have some urgent work to handle recently.)

You can change octree depth through:

https://github.com/DavidXu-JJ/PoissonRecon_GPU/blob/7f4b0fd8e0252a53782d3670c1f50fdb55df5ff7/main.cu#L69

**Comment by DavidXu-JJ** [comment]
Hi all, 

It seems that the problem mentioned in this issue comes from an unresolved bug from Thrust library. As is mentioned in https://github.com/PointCloudLibrary/pcl/issues/4700#issuecomment-819678140 .

The incompatibility of "driver, compute_arch setting" with other parts may lead to this bug in Thrust library.

Unfortunately since I have reinstalled my own PC environment(including the GPU driver), I'm unable to keep track on everything it used to be.

BTW, I don't solve the problem by pulling `nvcr.io/nvidia/cuda:12.2.2-cudnn8-devel-ubuntu22.04`.

I finally solve the problem by setting

https://github.com/DavidXu-JJ/PoissonRecon_GPU/blob/7f4b0fd8e0252a53782d3670c1f50fdb55df5ff7/CMakeLists.txt#L37

as 

```
target_compile_options(GPU_PoissonRecon PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-arch=sm_80>)
```

Everything goes well and the output on my PC is like:

```
/home/davidxu/PoissonRecon_GPU/cmake-build-debug/GPU_PoissonRecon
Total points number:362271 ,Read takes:0.108775s
GPU NodeArray build takes:0.183855s
NodeArray_sz:95009
CPU generate precomputed inner product table takes:0.024711s
Compute Vector Field takes:0.004791s
Precompute Function index of node takes:0.000478s
left:1513,right:95009
Compute finer depth nodes' divergence takes:0.003951s
Compute coarser depth nodes' divergence takes:0.101094s
Depth 0 Itetation...
valNums:1
Starting [conjugateGradientMultiBlockCG]...
> GPU device has 16 Multi-Processors, SM 8.6 compute capabilities

GPU Final, residual = 1.273569e-09, kernel execution time = 0.174432 ms
Test Summary:  Error amount = 0.000000 
Depth 1 Itetation...
valNums:64
Starting [conjugateGradientMultiBlockCG]...
> GPU device has 16 Multi-Processors, SM 8.6 compute capabilities

GPU Final, residual = 1.462843e-09, kernel execution time = 0.170528 ms
Test Summary:  Error amount = 0.250000 
Depth 2 Itetation...
valNums:1000
Starting [conjugateGradientMultiBlockCG]...
> GPU device has 16 Multi-Processors, SM 8.6 compute capabilities

GPU Final, residual = 2.973665e-07, kernel execution time = 0.410400 ms
Test Summary:  Error amount = 1.000000 
Depth 3 Itetation...
valNums:5752
Starting [conjugateGradientMultiBlockCG]...
> GPU device has 16 Multi-Processors, SM 8.6 compute capabilities

GPU Final, residual = 8.748028e-06, kernel execution time = 0.935008 ms
Test Summary:  Error amount = 1.000000 
Depth 4 Itetation...
valNums:22624
Starting [conjugateGradientMultiBlockCG]...
> GPU device has 16 Multi-Processors, SM 8.6 compute capabilities

GPU Final, residual = 9.181569e-06, kernel execution time = 1.315264 ms
Test Summary:  Error amount = 0.312500 
Depth 5 Itetation...
valNums:87708
Starting [conjugateGradientMultiBlockCG]...
> GPU device has 16 Multi-Processors, SM 8.6 compute capabilities

GPU Final, residual = 9.879643e-06, kernel execution time = 1.316512 ms
Test Summary:  Error amount = 0.312500 
Depth 6 Itetation...
valNums:347648
Starting [conjugateGradientMultiBlockCG]...
> GPU device has 16 Multi-Processors, SM 8.6 compute capabilities

GPU Final, residual = 8.213109e-06, kernel execution time = 6.947168 ms
Test Summary:  Error amount = 0.125000 
Depth 7 Itetation...
valNums:1397280
Starting [conjugateGradientMultiBlockCG]...
> GPU device has 16 Multi-Processors, SM 8.6 compute capabilities

GPU Final, residual = 8.008440e-06, kernel execution time = 22.185535 ms
Test Summary:  Error amount = 0.039062 
Pure CG solving process takes:33.454849ms
GPU Laplacian Iteration takes:0.064976s
isoValue:-49729232.000000
GPU calculate isoValue takes:0.027270s
VertexArray_sz:141986
GPU build VertexArray takes:0.007542s
EdgeArray_sz:285460
GPU build EdgeArray takes:0.007261s
FaceArray_sz:331862
GPU build FaceArray takes:0.003444s
Compute vertex implicit function value takes:0.017861s
Compute vexAddress takes:0.000467s
Compute triAddress takes:0.000122s
Generate interpolate vertices takes:0.048506s
Process Triangle indices takes:0.001263s
Starting processing the subdivide node
SubdivideNum:4141
GPU processing coarse subdivide nodes takes 0.089097s
Start the 3 depth finer subdivide nodes processing
Start the 4 depth finer subdivide nodes processing
Start the 5 depth finer subdivide nodes processing
Start the 6 depth finer subdivide nodes processing
GPU processing finer subdivide nodes takes 0.170295s
Output ply files takes 0.039360s
The whole project takes 0.905336s (including I/O)

Process finished with exit code 0
```

I have previously upgraded my driver, so it's reasonable to work after I compile with `compute_arch=sm_80`.

I personally think this problem can not just be resolved by configuring a dockerfile for this, because the cuda environment in docker container still depends on the GPU driver you install on your physical device.

My suggestion will be checking the compute_arch that's compatible with your driver and specific device.

**Comment by DavidXu-JJ** [comment]
Thanks all for reporting this problem.
